version: '3'
services:
  gophish:
    image: gophish/gophish:latest
    container_name: gophish
    ports:
      - "3333:3333"  # Change this port if needed
      - "80:80"      # HTTP web interface
    environment:
      - GOPHISH_SSL=false  # Set to true if you want to use HTTPS
    volumes:
      - gophish:/config  # Persist GoPhish configuration

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "443:443"  # HTTPS
      - "80:80"    # HTTP
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile  # Mount your Caddyfile for configuration
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
  gophish:

